# Generated by Django 2.1.1 on 2018-10-18 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='time_of_application',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 23, 16, 304307)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='time_of_selection',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 23, 16, 304726)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgfrom', to='Portal.CustomUser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgto', to='Portal.CustomUser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receivingTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 23, 16, 306540)),
        ),
        migrations.AlterField(
            model_name='project',
            name='postedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 23, 16, 302451)),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 23, 16, 302917)),
        ),
    ]
