# Generated by Django 2.1.1 on 2018-10-15 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='time_of_application',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 0, 31, 43, 985324)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='time_of_selection',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 0, 31, 44, 924)),
        ),
        migrations.AlterField(
            model_name='hoursofwork',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receivingTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 0, 31, 44, 924)),
        ),
        migrations.AlterField(
            model_name='project',
            name='postedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 0, 31, 43, 985324)),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 0, 31, 43, 985324)),
        ),
    ]
