# Generated by Django 2.1.1 on 2018-10-20 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='time_of_application',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 0, 24, 412809)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='time_of_selection',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 0, 24, 412809)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 0, 24, 412809)),
        ),
        migrations.AlterField(
            model_name='project',
            name='postedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 0, 24, 397178)),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 0, 24, 412809)),
        ),
    ]
