# Generated by Django 2.1.1 on 2018-10-19 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20181018_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='time_of_application',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 10, 53, 290273)),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='time_of_selection',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 10, 53, 290891)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 10, 53, 293704)),
        ),
        migrations.AlterField(
            model_name='project',
            name='postedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 10, 53, 288411)),
        ),
        migrations.AlterField(
            model_name='task',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 10, 53, 288883)),
        ),
    ]
